export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";
