export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
export const SET_NEXT_PAGE = "SET_NEXT_PAGE";
export const SET_PREVIOUS_PAGE = "SET_PREVIOUS_PAGE";
export const SET_FILTER = "SET_FILTER";
export const SET_SORT = "SET_SORT";
export const SET_BORDER_COLOR = "SET_BORDER_COLOR";
